//companyChat kısmındaki çoklu mesaj görünümünün elemanlarının veri deposu

final people = [
  {
    "id": 1,
    "phone": "544 836 4520",
    "email": "gokhankundala@gmail.com",
    "username": "gkhnkndl",
    "name": "Gökhan",
    "surname": "Kundala",
    "avatar": "assets/images/manhattan.jpg",
    "date": DateTime.now().add(Duration(minutes: -30)),
    "message": "Yarın toplantı saat 12:30'da başlayacak",
    "unread": "2",
    "position": "Operation Manager",
  },
  {
    "id": 2,
    "phone": "532 862 1623",
    "email": "alperenkeskin@gmail.com",
    "username": "alperen.keskin",
    "name": "Alperen",
    "surname": "Keskin",
    "avatar": "assets/images/hamsi.jpg",
    "date": DateTime.now().add(Duration(minutes: -50)),
    "message": "Kanka şirkete transit kamyonet alalım",
    "unread": "5",
    "position": "Driver",
  },
  {
    "id": 3,
    "phone": "538 888 1616",
    "email": "mstf.ince@gmail.com",
    "username": "mstfince",
    "name": "Mustafa",
    "surname": "İncekara",
    "avatar": "assets/images/berserk.jpg",
    "date": DateTime.now().add(Duration(minutes: -20)),
    "message": "Ne zaman iş biter gidip GTA 5 RP oynamak istiyorum",
    "unread": "2",
    "position": "Cost Control",
  },
  {
    "id": 4,
    "phone": "533 664 1896",
    "email": "kaganx@gmail.com",
    "username": "kaganusdf",
    "name": "Kağan",
    "surname": "Aydoğan",
    "avatar": "assets/images/nk.jpg",
    "date": DateTime.now().add(Duration(minutes: -32)),
    "message": "Beyler destek birimine gitmeyin sürekli",
    "unread": "4",
    "position": "Cost Control",
  },
  {
    "id": 5,
    "phone": "544 654 3216",
    "email": "congobiskn@gmail.com",
    "username": "cengomlayn",
    "name": "Cengizhan",
    "surname": "Güner",
    "avatar": "assets/images/gojo.webp",
    "date": DateTime.now().add(Duration(minutes: -43)),
    "message": "Abi ben yok ben bilmiyor",
    "unread": "1",
    "position": "Accountant",
  },
  {
    "id": 6,
    "phone": "544 511 3188",
    "email": "emrekrdmn@gmail.com",
    "username": "jun",
    "name": "Emre",
    "surname": "Karaduman",
    "avatar": "assets/images/gtr.jpg",
    "date": DateTime.now().add(Duration(minutes: -43)),
    "message": "Göko dışarı çıkacam gelcen mi",
    "unread": "2",
    "position": "Engineer",
  },
  {
    "id": 1,
    "phone": "544 836 4520",
    "email": "gokhankundala@gmail.com",
    "username": "gkhnkndl",
    "name": "Gökhan",
    "surname": "Kundala",
    "avatar": "assets/images/manhattan.jpg",
    "date": DateTime.now().add(Duration(minutes: -30)),
    "message": "Yarın toplantı saat 12:30'da başlayacak",
    "unread": "2",
    "position": "Operation Manager",
  },
  {
    "id": 2,
    "phone": "532 862 1623",
    "email": "alperenkeskin@gmail.com",
    "username": "alperen.keskin",
    "name": "Alperen",
    "surname": "Keskin",
    "avatar": "assets/images/hamsi.jpg",
    "date": DateTime.now().add(Duration(minutes: -50)),
    "message": "Kanka şirkete transit kamyonet alalım",
    "unread": "5",
    "position": "Driver",
  },
  {
    "id": 3,
    "phone": "538 888 1616",
    "email": "mstf.ince@gmail.com",
    "username": "mstfince",
    "name": "Mustafa",
    "surname": "İncekara",
    "avatar": "assets/images/berserk.jpg",
    "date": DateTime.now().add(Duration(minutes: -20)),
    "message": "Ne zaman iş biter gidip GTA 5 RP oynamak istiyorum",
    "unread": "2",
    "position": "Cost Control",
  },
  {
    "id": 4,
    "phone": "533 664 1896",
    "email": "kaganx@gmail.com",
    "username": "kaganusdf",
    "name": "Kağan",
    "surname": "Aydoğan",
    "avatar": "assets/images/nk.jpg",
    "date": DateTime.now().add(Duration(minutes: -32)),
    "message": "Beyler destek birimine gitmeyin sürekli",
    "unread": "4",
    "position": "Cost Control",
  },
  {
    "id": 5,
    "phone": "544 654 3216",
    "email": "congobiskn@gmail.com",
    "username": "cengomlayn",
    "name": "Cengizhan",
    "surname": "Güner",
    "avatar": "assets/images/gojo.webp",
    "date": DateTime.now().add(Duration(minutes: -43)),
    "message": "Abi ben yok ben bilmiyor",
    "unread": "1",
    "position": "Accountant",
  },
  {
    "id": 6,
    "phone": "544 511 3188",
    "email": "emrekrdmn@gmail.com",
    "username": "jun",
    "name": "Emre",
    "surname": "Karaduman",
    "avatar": "assets/images/gtr.jpg",
    "date": DateTime.now().add(Duration(minutes: -43)),
    "message": "Göko dışarı çıkacam gelcen mi",
    "unread": "2",
    "position": "Engineer",
  },
  {
    "id": 1,
    "phone": "544 836 4520",
    "email": "gokhankundala@gmail.com",
    "username": "gkhnkndl",
    "name": "Gökhan",
    "surname": "Kundala",
    "avatar": "assets/images/manhattan.jpg",
    "date": DateTime.now().add(Duration(minutes: -30)),
    "message": "Yarın toplantı saat 12:30'da başlayacak",
    "unread": "2",
    "position": "Operation Manager",
  },
  {
    "id": 2,
    "phone": "532 862 1623",
    "email": "alperenkeskin@gmail.com",
    "username": "alperen.keskin",
    "name": "Alperen",
    "surname": "Keskin",
    "avatar": "assets/images/hamsi.jpg",
    "date": DateTime.now().add(Duration(minutes: -50)),
    "message": "Kanka şirkete transit kamyonet alalım",
    "unread": "5",
    "position": "Driver",
  },
  {
    "id": 3,
    "phone": "538 888 1616",
    "email": "mstf.ince@gmail.com",
    "username": "mstfince",
    "name": "Mustafa",
    "surname": "İncekara",
    "avatar": "assets/images/berserk.jpg",
    "date": DateTime.now().add(Duration(minutes: -20)),
    "message": "Ne zaman iş biter gidip GTA 5 RP oynamak istiyorum",
    "unread": "2",
    "position": "Cost Control",
  },
  {
    "id": 4,
    "phone": "533 664 1896",
    "email": "kaganx@gmail.com",
    "username": "kaganusdf",
    "name": "Kağan",
    "surname": "Aydoğan",
    "avatar": "assets/images/nk.jpg",
    "date": DateTime.now().add(Duration(minutes: -32)),
    "message": "Beyler destek birimine gitmeyin sürekli",
    "unread": "4",
    "position": "Cost Control",
  },
  {
    "id": 5,
    "phone": "544 654 3216",
    "email": "congobiskn@gmail.com",
    "username": "cengomlayn",
    "name": "Cengizhan",
    "surname": "Güner",
    "avatar": "assets/images/gojo.webp",
    "date": DateTime.now().add(Duration(minutes: -43)),
    "message": "Abi ben yok ben bilmiyor",
    "unread": "1",
    "position": "Accountant",
  },
  {
    "id": 6,
    "phone": "544 511 3188",
    "email": "emrekrdmn@gmail.com",
    "username": "jun",
    "name": "Emre",
    "surname": "Karaduman",
    "avatar": "assets/images/gtr.jpg",
    "date": DateTime.now().add(Duration(minutes: -43)),
    "message": "Göko dışarı çıkacam gelcen mi",
    "unread": "2",
    "position": "Engineer",
  },
];
